
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: recruitment_app
  password: secret
  host: localhost

development:
  <<: *default

  database: recruitment_app_development
  
test:
  <<: *default

  database: recruitment_app_testing